# docker-compose.yml

version: "3.8"

services:
  web:
    build: .
    ports:
      - "81:81"
    depends_on:
      - db

  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: gamestore # The PostgreSQL database name
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
