# docker-compose.yml

version: "3.8"

services:
  web:
    build: .
    ports:
      - "81:81"
    depends_on:
      - db

  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gamestore
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
